language: python
sudo: required # For overwriting /etc/hosts, to test hostname based routing.

python:
- 2.7
- 3.6
env:
  matrix:
    - DJANGO_VERSION='1.8.19'  # LTS
    - DJANGO_VERSION='1.11.11'  # LTS
    - DJANGO_VERSION='2.0.3'  # not LTS
matrix:
  fast_finish: true
  exclude:
    - env: DJANGO_VERSION='2.0.3'
      python: 2.7  # only python3

install:
- pip install -r requirements-dev.txt
# Load pinned versions first, and get dependencies for setup.py
- pip install -r requirements.txt

before_script:
- set -o errexit
- pip install django==$DJANGO_VERSION
- sudo sh -c 'echo "127.0.0.1 container-name.docker.localhost" >> /etc/hosts'
script: ./test.sh
after_success: codecov
deploy:
  # Defaults to only deploy on master;
  # PyPi blocks the same version from being uploaded twice.
  provider: pypi
  distributions: sdist bdist_wheel
  user: mccalluc
  password:
    secure: "SIHqHXYTyCWJ6hfdvzheVZpsUvjCkUuoUMl5kqvek9Rk8jA3TYl4Lx4JVKtWpE8kjPJ5XlvPIfPh0dL+awZj5VYpqRryo2B0Ef1zx1pEIEn5kByr2lpki2fDibNmOeoUSrhVDtKeAkJaN/fIs3IklSrPEw5WspiQo/h8yZ2THg5roiueugKRm3YYUHq21zuWOGjNCGBaaLGJk8GJmv+Vgc3eRcVOyBqC0uCZtvw+d7pz+V7Oh9YjHXNYvbTH5q+K01xL+ixM1LcmAy0f/rPTH76fzKxk4rkRoGBd4XXqFFfAwc5bdwzLX5hjeTUN3Eu/XNsdb/84u4vxXjCKXleLHXzltQACiCyySBughUxBYh6GsWis+rIllHYJRtIkeAmPyb6rWBP5LTdEIBm4YifQ/KuRm5sLUBkFxYfCFqZUD2FpXVYHuc+4OE5cbtAXSF+y2pH4QHAmc8En6W7mRatu8r6qltdXd9nhtk3V90nzVkd+lpdrkzOznM78mJcRm1XPnqz067KqyUZEnxLJIpqX8XCqV32xJMt/rCD2EIy0asyZG+yfH3Jx3QpvFMdMZbbjmc+Dlw2VCMJs3o0aHBSC4VDCzm1iwoVnGS02yCfSLwcWSw6FaDshJb/g8GmHc11BNW0ZpXwuES/1Nvlgqxtfy1c0RHqxf4loy2Q7m57jXXQ="
  on:
    branch: master
    python: 3.6
    condition: $DJANGO_VERSION = '1.11.11'