language: python
python:
- 2.7
sudo: required # TODO: Remind me why?
services:
- docker
install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
- start() { echo travis_fold':'start:$1; echo 'start:' $1; }
- end() { echo travis_fold':'end:$1; }
env:
  matrix:
    - VERSION='1.7.1'
    - VERSION='1.11.5'
matrix:
  fast_finish: true
script:
- set -o errexit

- cat /etc/hosts
- ping -c1 localhost
- sudo sh -c 'echo "127.0.0.1 foobar" >> /etc/hosts'
- ping -c1 foobar

- docker info | grep 'Operating System'  # Are we able to connect to Docker, and what OS is it?
- pip install django==$VERSION

- start test;   ./manage.py test --verbosity=2; end test
- start format; flake8;                         end format
- start egg;    python setup.py bdist_egg;      end egg
# TODO: No output on travis: Is pydoc installed?
#- start docs;        diff <(./docs.sh) docs.md; end docs
deploy:
  # Defaults to only deploy on master;
  # PyPi blocks the same version from being uploaded twice.
  provider: pypi
  user: mccalluc
  password:
    secure: Lo7Y4U+ozwrDyqWSTO6wcrbB1XK18y8bEMb5mNcUQaytoXJLxVrjyPEOlRln8DlNjtGWpcZW6gKomfuOqZziQLe+UdMV3h1HRLXnxNhy1YtZ74ZveZPl+sgKAmX5dsNQ6QocJdkcu82a+3xvVq07z/jrnX6He3QvO10LyGyYiTfZt723ZV1o6+cc6hk97tMkIC42N6wD5qCxCc7ijT5NNXnQ414OtCBZYSx0CwoAAym7cN6WdZdDHyKN3HFo+Kz+bBorMFvJ4voOYcarFXX9g6OH1+R2MG1Ub3POWSg3iJojg1RQc2JRd0E/HSCCcD2YaLHGUDwcY4Yfmi/8zXRpAQGAYP6WNZ+tFl/sxpkCwEsEiRTObEHKe4fR+DNt1V7G+/bvJF8g4xJLOEhetditNG6Qi5C/EmDGBhOE43hhR1x6I23FnKH6fnk7LYSP3dYPPLR9MLsthCUGVhSvQtKYU6UDech38JG7EFDIbk4JzuiT2YuoA+X2RVrJyDShDO0nBw2IPuZuj1k92tA61y7TWkXBlZSBv79EdGvuayCkAF/zt5Q1Fpj6t2P/BWE0g+7bu2lJrCp4YHGMLHZlF5muSyLZMkxe2b8fYO5LW2PMMoDbGTIJXdOGkwvVEc+22ivPckdi4psvHGcezlCwT7YIkNcH+xhgHQOWoPr3tO/U/bY=
