language: python
python:
- 2.7
sudo: required # TODO: Remind me why?
services:
- docker
install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
- start() { echo travis_fold':'start:$1; echo 'start:' $1; }
- end() { echo travis_fold':'end:$1; }
script:
- |-
  set -o errexit

  for VERSION in '1.7.1' '1.10.6'; do
    start docker-$WHERE_IS_DOCKER-django-$VERSION
    pip install django==$VERSION
    docker info | grep 'Operating System'  # Are we able to connect to Docker, and what OS is it?
    python manage.py test tests --verbosity=2
    end docker-$WHERE_IS_DOCKER-django-$VERSION
  done

  start format
  flake8
  end format

  start egg
  python setup.py bdist_egg
  end egg
