language: python
python:
  - 2.7

sudo: required
services:
  - docker

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - set -o errexit
  - |-
      for VERSION in '1.7.1' '1.8.17' '1.9.12' '1.10.6'; do
        echo "travis_fold:start:$VERSION"
        pip install django==$VERSION
        python manage.py test --verbosity=2
        echo "travis_fold:end:$VERSION"
      done
  - flake8
